### ISSUE TITLE
Support for modified CSS and HTML files?

### ISSUE THREAD

**Issue by pedro93** [gmetais/sw-delta#5]
How well does this the current implementation deal with modified HTML and CSS files? From what I've seen of the repository code, the main use is modified JavaScript asset files.

Wouldn't a reasonable use case for diff updates also be relative to changes in HTML? For instance an updated index.html where the footer or header are different?

Are these cases being considered? I know the project is just in its infancy but it would seem very limiting to only support JS libraries.

**Comment by gmetais** [comment]
Yes, it fully supports CSS and HTML files. All text files actually.

What made you think it wasn't the case in the doc?

**Comment by pedro93** [comment]
Nothing explicit on the docs, all mentions of the patch were relative to JavaScript files.
I also noticed that you use [diff match patch](https://code.google.com/p/google-diff-match-patch/wiki/API) library which is text based. For files such as HTML which are tree based, whitespace and attribute re-orders for example, at an element level are innocuous but appear with text based diffing.
Are these false positives being taken into consideration?

**Comment by gmetais** [comment]
No they're not, and it seems to me it would be a big amount of work for a small result.
